### ISSUE TITLE
Bump to PHP 8.3

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-cache#15]

**Comment by bidi47** [comment]
blocked by 
laminas/laminas-cache-storage-adapter-filesystem
laminas/laminas-cache-storage-adapter-session

**Comment by arhimede** [comment]
upstream packages was releases to support PHP 8.3

https://github.com/laminas/laminas-cache-storage-adapter-filesystem/releases/tag/2.4.0
https://github.com/laminas/laminas-cache-storage-adapter-session/releases/tag/2.5.0

**Comment by arhimede** [comment]
fixed in #16
